{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kiwiki.fullname" . }}-secret
  labels:
    {{- include "kiwiki.labels" . | nindent 4 }}
type: Opaque
stringData:
  KIWIKI_USERS: {{ required "secretEnv.KIWIKI_USERS or existingSecret must be set" .Values.secretEnv.KIWIKI_USERS | quote }}
  KIWIKI_OAUTH_TOKEN_SECRET: {{ required "secretEnv.KIWIKI_OAUTH_TOKEN_SECRET or existingSecret must be set" .Values.secretEnv.KIWIKI_OAUTH_TOKEN_SECRET | quote }}
{{- end }}
